### ISSUE TITLE
Screenshot "Add a caption" box placeholder text is misaligned

### ISSUE THREAD

**Issue by FlaminSarge** [DirtDiglett/Pressure-for-Steam#156]
See:
http://cloud-4.steamusercontent.com/ugc/38612695649314108/15DCE62EDEFC8ED88C4B46189207BA7203E09C08/

The "Add a caption" text doesn't seem to be positioned properly.

It's also worth noting that when that box is clicked, the cursor appears in the very top left of the box, but once a character is typed, the characters are placed such that the box does appear to have proper padding around the edges (that is, the initial cursor isn't positioned properly either, though characters typed into the box are).

**Comment by FlaminSarge** [comment]
Possibly tied to
resource/layout/screenshotmanager.layout#L335

**Comment by Asphira** [comment]
Hi flaming sarge, i think I might work on this one as well as one of my other updates,

**Comment by DirtDiglett** [comment]
Valve did a very spastic thing for that input. Instead of just addingthe ability to have 'placeholder' text for text boxes they decided to overlay two text boxes on top of each other. This had other weird background behaviour and this is just the compromise I made at the time. If @Asphira fixes it then that's great.

**Comment by CaptainMagma** [comment]
I've been meaning to ask is there a reason the text is so pixelated inside text boxes like this one when in the Steam overlay? The URL bar in the Steam browser would be another example.

**Comment by Zerathos** [comment]
If I remember right, it's because DirectWrite isn't used in the overlay.

**Comment by CaptainMagma** [comment]
It isn't used in the overlay in general or it is somehow disabled for this skin? Because this is the only skin I've used that causes the font to look this way.

**Comment by Zerathos** [comment]
It's an issue present in a few skins. It was brought up in #53.

**Comment by CaptainMagma** [comment]
Oh, I see now. DirectWrite seems to have a harder time smoothing out the font with the white background behind text. Thanks for the response.

**Comment by DirtDiglett** [comment]
Valve chose to disable DirectWrite in the overlay in order to fix a performance drop with it enabled in the overlay. This means that text on the overlay uses a crappier anti-aliasing method and generally looks poorer quality. It looks ok when it is light text on a dark background but looks terrible with dark text on a light background which is why it's more noticable on Pressure than default Steam.
