### ISSUE TITLE
Logging into friends will hang steam

### ISSUE THREAD

**Issue by SkacikPL** [DirtDiglett/Pressure-for-Steam#165]
On random occasions, logging into steam friends module will freeze the entire application when using pressure.

**Comment by DirtDiglett** [comment]
That's a very weird bug. Is it something you can reliably reproduce (As in, it occurs every time if steam drops out while logged in) or something that happens sporadically?

**Comment by Zerathos** [comment]
I've had this happen before, and it only happens sometimes, and only happens close to when Steam has started. Hard to say if it's Pressure though, since I rarely use anything else to see if it happens there, and I'm also using the beta client which could be a factor.

**Comment by Js41637** [comment]
What do you mean logging into friends? Like when you're in display offline and you click sign in?

**Comment by SkacikPL** [comment]
Whilst i don't know all possible combinations, i know this one will occur pretty often (but still not always):
If you disable the option to login into friends automatically as steam starts, then at random if you try to login to friends after starting steam this issue will occur.

**Comment by FlaminSarge** [comment]
Possibly related to missing some notification panel? (You know, like "X has invited you to group Y" that shows up in the bottom right).

**Comment by notnsane** [comment]
This happens to me randomly not when joining the Friends list (it's on auto an it never happens) but when trying to join a chat room.

It's too annoying, I have to stop using this skin until this is fixed.

**Comment by FlaminSarge** [comment]
Oh, a CHAT room?

**Comment by becky-soda** [comment]
I am also receiving this issue. I've tried looking for crash dumps, but the "...\Steam\Dumps\" folder is always empty.

It happens every single time for me. It happens regardless of whether the computer has just been rebooted or not, and whether Steam has been freshly started or not. I even tried removing all other skins I have installed, and I've tried deleting all of the files in the Steam folder except "Steam.exe", "Steamapps\" and "Userdata\" (just to make sure that there isn't some extra file lurking somewhere that is causing the crash).

All other skins work fine, and seem to allow me to sign in without problem. I have tested "Air", "Metro" and "PixelVision", as well as the default/generic Steam skin.

I don't know if it helps, but here is a video demonstrating the crash: https://www.youtube.com/watch?v=ZDjt6i8aZk8

**Comment by Js41637** [comment]
Are you on the public or Beta Client? Do you use any special friend settings like Sort by Name, Show Avatar, Show Online Only, Display in all Friends?

**Comment by becky-soda** [comment]
Thanks for the reply Js41637! ^-^

I'm on the main Steam client, not the beta client. I haven't really set anything unusual in the sort order. "Show Avatars" is enabled/ticked, but "Sort by Name", "Show Online Friends Only" and "Show All in the Friends Section" are disabled/unticked. If I set "Automatically Sign into Friends when I start Steam" to enabled/ticked, then everything works fine and I can go "Offline" and "Sign In" without problems. But as soon as I disable/untick "Automatically Sign into Friends when I start Steam", restart Steam, and then try to manually sign in, then it crashes.

I have also tested the skin with another account that has no friends. Clicking the "Sign In" button when I am logged into the 'friendless' account works fine, and doesn't cause the crash.

I have also noticed when I click "Sign In" on the normal account and a non-Pressure skin, I see a lot of notifications pop up... I actually have a moderate number of friends, and I usually see a lot of them signed in and playing games. I tried turning off all the notifications, restarting Steam, and testing it again but it still causes the crash. In other words, I don't think it's the toaster pop-ups causing the issue.

**Comment by Zerathos** [comment]
>I have also tested the skin with another account that has no friends. Clicking the "Sign In" button when I am logged into the 'friendless' account works fine, and doesn't cause the crash.

This, in addition to the fact that you get it every time, is interesting. How many friends do you have? I have 66, and as previously mentioned only get this every once in a while. If you have a very large list of friends it might go some way to explaining this. Steam doesn't handle large lists very well (for example, if you have a lot of games, activating Steam keys will hang the client).

I have have all friend-related notifications turned off, no toasts. So it might not be that, or it might be be that there are two issues, and the toasts are the reason you get a crash every time, and I only get them occasionally.

**Comment by Js41637** [comment]
This is a very weird bug, we know Skins can crash Steam if certain things are wrong but this seems to affect a very small number of people, I cannot reproduce this at all.

**Comment by DirtDiglett** [comment]
I also cannot reproduce the issue, even following what you showed in the YouTube video (Thanks for that, makes it even easier to understand where it's going wrong).

So for those of you who experience the issue by doing the youtube video's method, can you please go into the Skin, find the friends folder and inside there delete the file "Friendsdialog.layout", and restart Steam and tell me if the issue continues. If so, delete the entire friends folder and restart and also let me know if it still occurs after this.

Thanks guys!

**Comment by becky-soda** [comment]
@Zerathos I have 62 friends, so slightly less than yourself.

@DirtDiglett I couldn't find "Friendsdialog.layout", but I deleting the "Friendsdialog.res" file, and that didn't help. (I think I deleted the right file, because the Friends dialog box's appearance changed thus: http://imgur.com/87A5XDa ). I tried deleting the whole Friends folder, and that didn't help either. In both cases, Steam froze up again.

I tried something else: I considered that having custom friends groups/tags might be causing the problem, so I untagged all my friends. That didn't help.

I tried another thing: if I untick "Show Avatars", then click "Sign in", everything works as intended and Steam doesn't crash! ^.^

So, the basic workaround that works for me right now is to click the menu, disable/untick "Show Avatars", click the "Sign in" button, then click the menu again, and re-enable/retick "Show Avatars". Some quick testing shows that this works. Just to be sure, I restarted Steam again and tried to sign in with "Show Avatars" enabled/ticked, and it crashed. So it seems consistent and reproducible (from my end) that something about the "Show Avatars" function is causing the crash.

**Comment by Js41637** [comment]
Friends is a bit weird, `FriendsDialog.res` is under the `friends` and there is also the friends panel layout which is in `resource\layout` and called `friendspanel.layout`

**Comment by becky-soda** [comment]
@Js41637 Ah, thank you. So, I tried restarting Steam with "friendspanel.layout" deleted, rather than "Friendsdialog.res", and that also stops the crash. This is strange.

**Comment by DirtDiglett** [comment]
Not really, that actually makes sense based on what you mentioned. Friendspanel.layout handles how individual friend's avatar, name, game, etc. is layered so if having avatars off makes it work then it is definitely an issue inside Friendspanel.layout that is the problem.

I'm at work at the moment but when I get home I'll work out a fix and upload it :)

**Comment by becky-soda** [comment]
@DirtDiglett Thank you so, so much! I really appreciate your help, and the help of everyone else. ^-^

I think I've narrowed down the fault, but I don't understand *why* it is a fault...

Using a process of elimination (and restarting Steam over and over and over again ^.~) I managed to work out that one particular line seems to cause the crash. If I comment out line 107 (`font-style="outerglow"` under the `namestyle` section), it fixes it. I don't understand how or why, but commenting that line out fixes it for me.

**Comment by DirtDiglett** [comment]
I'll have to test when I get home, but speculating I doubt it's specifically the outer glow but the properties that have been used for the outer glow causing an issue, so I'll do a bit of tinkering and get it working and still nice and pretty.

**Comment by becky-soda** [comment]
Thanks again!

I don't know if this is helpful, but I tried commenting out the properties for that particular instance of outer glow. If I remove the double-forward-slash comments from `font-style="outerglow"`, and add double-forward-slash comments for `font-outerglow-color="darkestGrey"`, `font-outerglow-offset=1`, and `font-outerglow-filtersize=3` then it still crashes. I do, however, see that my changes are being interpreted and understood by the Steam client, because when I set it up this way I can see the outerglow effect being applied to my username, but rather than being a soft grey glow ("darkestGrey") it's a rather stark bright-white glow. But, again, when I try to "sign in", it crashes.

Just so you know, I'm not trying to hassle you, or spam your thread, I'm just trying to eliminate some possibilities for you. (Especially given that you can't seem to reproduce the problem.)
