### ISSUE TITLE
No "View players" option in Steam ingame (Alt+Tab)

### ISSUE THREAD

**Issue by Jorchking** [DirtDiglett/Pressure-for-Steam#173]
![insurgency 2015-02-04 02-03-07-84](https://cloud.githubusercontent.com/assets/8688412/6035462/b208394e-ac12-11e4-9a92-e47e1889a42c.jpg)

Isn't this feature in the latest version. Need a fix.

Thank you.

**Comment by Zerathos** [comment]
See #125.

**Comment by Jorchking** [comment]
So, what's mean that, will not be available anymore? o_o

**Comment by Zerathos** [comment]
Yes.

**Comment by Jorchking** [comment]
I see, uninstalling.

**Comment by DirtDiglett** [comment]
@Jorchking I'm waiting on Valve to change it so that it opens the website version (http://steamcommunity.com/my/friends/coplay) instead of the EXTREMELY buggy dialog window before I add it back. I'd suggest remembering that URL to view it in the meantime as Valve has given up working on the players dialog and only fix the website version themselves.

**Comment by Jorchking** [comment]
Thanks for the answer, well now I know exactly that issue, I know that were problems with that feature, anyway I'm using a lot.
Now I have to wait the fix. I don't know if was working fine before the feature, it was?

**Comment by DirtDiglett** [comment]
I don't understand your last sentence's question - can you please rephrase it for me.

**Comment by Jorchking** [comment]
@DirtDiglett If the "View players" was working fine some time?

**Comment by DirtDiglett** [comment]
Yes I'll add it when it works properly
