### ISSUE TITLE
Steam Settings Interface tab Bug

### ISSUE THREAD

**Issue by Sleekman1** [DirtDiglett/Pressure-for-Steam#181]
Lol, that is crazy lookin'.
![untitled](https://cloud.githubusercontent.com/assets/9705092/6074331/2ade1552-ad79-11e4-811a-896a71ba7c14.png)

**Comment by Zerathos** [comment]
What version of the skin are you using? I can't replicate this, and I just updated to the most recent commit. Also, are you in the Steam beta client (I am) or not?

**Comment by Sleekman1** [comment]
I did just update to the most recent version (2 minutes before i saw this), and I am not using the Steam Beta client.

**Comment by Zerathos** [comment]
Alright. Beta client might be it. I suspect PR #177 doesn't account for non-beta client users, so because you don't have the extra option it gets all out line.

**Comment by Sleekman1** [comment]
Most likely. Just wanted to let you guys know about it since i was browsing through the steam settings.

**Comment by Js41637** [comment]
I was just thinking about this, Dirt may want to think about creating another branch for the beta client and revert this branch back to the stable/public steam version.

**Comment by DirtDiglett** [comment]
The trouble is that there's no way to make a skin work for both at the same time... since the beta changes usually either entirely replace or add new controls so targeting these stuff up the non-beta skin look.

Since the skin itself is in 'beta' I'm leaning more towards keeping it up to date with the beta client since those changes will be getting merged into the main Steam client shortly anyway.

In the meantime, jump into the beta client and enjoy all the new stuff before others :)
