### ISSUE TITLE
Game details lack shaded bar, other issues for Non-Steam games

### ISSUE THREAD

**Issue by FlaminSarge** [DirtDiglett/Pressure-for-Steam#183]
See:
http://i.imgur.com/4lpyjUc.png (Non-Steam)
vs
http://i.imgur.com/oGlgeEE.png (Steam)
The positioning is also a bit different.

**Comment by DirtDiglett** [comment]
There are a few things at play here:

1) The shaded bar appears because for me to create it I had to 'link' it to some labels that only appear for steam games, so this is why it's not there currently. I am looking into a way around this.

2) The buttons get slightly different alignments based on the scrollbar existing or not. It's a bit spastic but it 'works' for now.

**Comment by DirtDiglett** [comment]
Hey @FlaminSarge I've fixed the lack of the shaded bar, the positioning will be fixed after I finish the re-work of the overall layout which I'm doing now.
