### ISSUE TITLE
[Mac] Gui and some design thinking

### ISSUE THREAD

**Issue by robos** [DirtDiglett/Pressure-for-Steam#207]
Hi, good job so far.

Few little things i noticed (Beta and no Beta Steam Client):

-there are vertical lines on both windows, each time going over the search field and beyond. You see that in the picture. (And i never had this search field on the friends windows and do not like it there-somehow optional would be great)

-something about the design or colouring: on the friends window, I think it would be more fitting, if the "Freunde" and "Gruppen" buttons styles would be exactly the opposite way around. If you have a look on the picture, you actually rather think, the selected tab would actually be "Gruppen" and not "Freunde". 

![bildschirmfoto 2015-02-18 um 22 29 57](https://cloud.githubusercontent.com/assets/11066425/6257558/6c87df90-b7c1-11e4-9463-1f866232e305.jpg)

**Comment by Zerathos** [comment]
The vertical lines are a known issue on Macs, see #33.

**Comment by DirtDiglett** [comment]
I'm guessing you have a retina display Mac? The vertical line issue only affects retina display and at this stage i'm not sure why. I would like to do some testing specifically on a retina Mac to try to fix it but I don't own one :-1: 

If you want to help me fix this add me on Steam and I can send you some files that *may* fix it, and that way if they do I can push it globally via Git.

For the second query regarding the selected and not selected buttons, if you take a look at the buttons used to switch between Game Details, Game List, and Game Grid you'll see it matches these. The "Active" button is 'pressed in'.

**Comment by robos** [comment]
Sorry, I didn't the the old thread.

DirtDiglett, I added you on Steam,glad if I can help.

About the Design, compared with that, it makes sense, though the friends window alone doesn't.  However, not a great bummer anyways :)

**Comment by robos** [comment]
Found something else, possibly related to Retina? The font on the overlay isn't sharp.

I copy and pasted a Screenshot from the desktop look for comparison, both, desktop and ingame resolution is 1920:1200 (over the 2880:1440 Screen Pixels)

![bildschirmfoto 2015-02-19 um 19 46 15](https://cloud.githubusercontent.com/assets/11066425/6273586/e0fbc1a2-b870-11e4-8f6c-f8c644c3fbc8.png)

**Comment by StamSolid** [comment]
Sorry for the hijack but since you guys talking about fonts and stuff I want to point it out that the wallet area (at least for me) isn't that clean. The € symbol drops a shadow on the last digit. Bebas Neue Bold font is installed. *Windows 7 x64 / 1920x1080*.
![](http://i.imgur.com/FFPNDum.png)

**Comment by DirtDiglett** [comment]
So I've been experimenting with Robos and come up with a potential solution. The line issue occurs only on elements with a 1-pixel wide repeating image and this causes lines because on a Retina display Mac Steam will use a 2x2 pixel grid, thereby avoiding it looking super tiny on a Retina display but it appears Valve didn't account for this when using a repeating image so a 1pixel wide image will repeat every second pixel creating the gap. The fix will be to use a multiple-pixel wide image repeating but this causes some weird offsets I need to fix before adding it to the main branch.

To answer the other queries in this thread:
>Found something else, possibly related to Retina? The font on the overlay isn't sharp.
This is nothing specific to Pressure. The in-game overlay uses a weaker font render system due to performance issues that Valve were unable to comfortable resolve so they used a weaker font renderer to improve stability and speed specifically in the Overlay. It's usually hard to notice on default Steam because they use colors that have a lack in contrast making it difficult to see, but I have high contrast color choices that make it more obvious unfortunately.

>And is it possible to get the Tabs and the window controls (close, maximize and minimize) in on line? Would make the the space better used.
No, this has been asked a few times around the place and there seems to be a bit of confusion regarding this. There is actually more utilized space on the skin for chats than on Steam's default skin. http://i.imgur.com/cN1sKTI.png
Both default Steam and Pressure side-by-side with the same sized Window. The header area you're referencing only takes up 8 pixels more than default Steam, but has the added benefit of being easily 'grabbed' and moved even when there are 10 chat tabs open. With default Steam if you have 10 chat tabs open you only have a teeny tiny area to move the window with.

Secondly, even with this extra 8 pixels of space taken up there is still more room for the chat than default Steam, it is lacking excessive borders and provides 186 pixels height in the window for chat as opposed to Steam's 179. Essentially, it's an illusion that it's taking up more space when in reality it is using more.


@StamSolid Can you provide a screenshot for the same currency bit on default Steam please.

**Comment by DirtDiglett** [comment]
Can everyone with a Retina Display please try the version of the skin on this repo: https://github.com/DirtDiglett/Pressure-for-Steam--Retina-Test- and submit issues to it.

The first copy from this repo should hopefully fix the search bar specifically, if it does I can proceed ot fixing everywhere else it affects too.

Thanks.

@robos 
@StamSolid

**Comment by robos** [comment]
It doesn't fix it, only changes it :/

Want the details here or shall I open an Issue over there?

**Comment by DirtDiglett** [comment]
Either or. What do you mean by changes it?

**Comment by robos** [comment]
![bildschirmfoto 2015-03-27 um 12 03 22](https://cloud.githubusercontent.com/assets/11066425/6866511/607df80e-d479-11e4-887b-36ade31bb05d.png)

Have a look at this image

**Comment by robos** [comment]
![bildschirmfoto 2015-03-27 um 14 23 01](https://cloud.githubusercontent.com/assets/11066425/6868819/0520aab8-d48f-11e4-9690-5db77b371c52.png)

**Comment by robos** [comment]
u are getting there :) 
notice the discrepancy on the right side of the search field?

![bildschirmfoto 2015-03-27 um 14 40 20](https://cloud.githubusercontent.com/assets/11066425/6868859/545b8774-d48f-11e4-9d52-8e0b54e6d64f.png)

**Comment by robos** [comment]
![bildschirmfoto 2015-03-27 um 14 48 58](https://cloud.githubusercontent.com/assets/11066425/6868978/7763ff5c-d490-11e4-9ba4-e6dbae664e7e.png)

**Comment by robos** [comment]
![bildschirmfoto 2015-03-27 um 14 52 58](https://cloud.githubusercontent.com/assets/11066425/6869026/0057b29a-d491-11e4-892b-46f1c4ef127c.png)

**Comment by robos** [comment]
![bildschirmfoto 2015-03-27 um 14 59 45](https://cloud.githubusercontent.com/assets/11066425/6869134/f64e68ec-d491-11e4-9a5a-ea9ab600531f.png)

**Comment by robos** [comment]
![bildschirmfoto 2015-03-27 um 15 24 18](https://cloud.githubusercontent.com/assets/11066425/6869563/6a7d9a64-d495-11e4-8ae3-812b100fb45d.png)
