### ISSUE TITLE
Missing labels in Non-Steam Game overlay

### ISSUE THREAD

**Issue by buttputt** [DirtDiglett/Pressure-for-Steam#209]
As seen here:
![9545992486762053632_screenshots_2015-02-19_00001](https://cloud.githubusercontent.com/assets/9625866/6279699/a9eb66b4-b86a-11e4-9264-54738270c4c0.jpg)

The name of the game being played is not being shown on the overlay.

**Comment by DirtDiglett** [comment]
That's really weird, there's no off-the-top-of-my-head explanation as to why but I'll take a look and get it sorted :+1:

**Comment by DirtDiglett** [comment]
In a follow-up from this @Js41637 has confirmed the regular Steam on default skin has the same issue, it appears to be expected behaviour. I always thought it did so assumed this was an issue.

![ss 2015-03-26 at 03 09 05](https://cloud.githubusercontent.com/assets/3527401/6840356/1c891532-d3c2-11e4-92c2-68967118d571.jpg)
