### ISSUE TITLE
Misaligned text in library for hours played 

### ISSUE THREAD

**Issue by LordFatBastard** [DirtDiglett/Pressure-for-Steam#214]
![](http://i.imgur.com/ItS1Sro.png)

The text that displays the hours played for a game is not aligned with the text below that displays last time played, may be deliberate.

**Comment by Js41637** [comment]
I think this is another Steam issue that is outside of the Skins control.

**Comment by DirtDiglett** [comment]
This is how Valve have made these labels. This is the same alignment as seen in the default Steam skin. Unfortunately it cannot be changed to be truly left aligned and that's why other skins have it centered instead (Air, Metro, etc.) but I want it on the side here. This is behaving as expected so I'm closing this.
