### ISSUE TITLE
Some graphical bugs

### ISSUE THREAD

**Issue by Holly-Chan** [DirtDiglett/Pressure-for-Steam#241]
Hey Diglet !

Just downloaded the latest commit. Love the new look!

I was using this skin and i didn't report these, but since the full release is near, might as well report them now.
 
The last window of a game's installation is missing a button

![b](https://cloud.githubusercontent.com/assets/9482398/6958331/7510b930-d8e0-11e4-8cd3-499f3c7f5597.PNG)

there is a black border missing from the reload/stop button when you open a window with the middle mouse button

how it is:
![a](https://cloud.githubusercontent.com/assets/9482398/6958359/28a4d4e0-d8e1-11e4-865f-b3d3a2ae71df.PNG)

how it is supposed to be:

![d](https://cloud.githubusercontent.com/assets/9482398/6958360/3156c15c-d8e1-11e4-93e5-e4012c0a37ab.PNG)

The phone icon was overlapping the steam user name on my friend's list. I dont know if you fixed it and i dont have anyone logged through a phone to show an image. Sorry about that.

Other Stuff:

Remember when i said how the skin was "lagging" in the game's grid page? You said that this could be fixed by adjusting the mouse speed. Did you do it? I think the skin needs to be a little "smoother" (like the default skin), so the user feels that the skin is fast and light on the system.

Anyway, thanks again for your work on the skin, it is the best looking skin so far for me.

**Comment by DirtDiglett** [comment]
Somehow I completely forgot to add disabled images for when the close/maximize/etc. buttons were disabled... I've added them so that's fixed up now.

I've also done some re-work on the popup browser so it should fit the rest of the skin better now.

@FlaminSarge has been working on the friends names and stuff so the misaligned phone/web/etc. icons should be fixed up after I merge his changes in shortly.

In regards to the grid view, unfortunately I can't remember nor can I easily find where we discussed it sorry :cry: However, i've not noticed any lag on the grid view after some testing so it may be sorted out already? There's so much I'd love to do with the grid view but it's such a hacky disgusting mess it's rediculous. I want to do this: http://i.imgur.com/0JVSeIl.jpg but the problem is that it's done inside a control so it's not applied via a skin :-1:

**Comment by Holly-Chan** [comment]
Hey thanks for the fixes ! 

As to where we discussed, it was here #118 in the "Another thing i like to ask".

Well i can feel like it is not a smooth as the default skin when scrooling but thats not a big problem, as it is definitely more smoother than it was before.

But thanks anyway, as a said it is for me the best skin out there.
