### ISSUE TITLE
Shortcut Keys in Settings Broken

### ISSUE THREAD

**Issue by CorruptComputer** [DirtDiglett/Pressure-for-Steam#251]
Whenever I was flipping through my settings I noticed this: http://i.gyazo.com/4563cda48b89a5bc3343dedae4f56458.png

The shortcut keys are blank. I just switched to the default skin and they are properly filled in. Switching back to Pressure they are blank again.

**Comment by FlaminSarge** [comment]
I've got this too, I'm trying to figure out if Valve changed anything in a recent Beta update.

**Comment by Js41637** [comment]
Been like this for a while if I recall and it's not just this part, any text entry similar to this one, push to talk is like this. I've actually just spend 15 mins trying to figure out why no text is showing and I have no idea, i've removed the styles, added extra stuff but nothing. Default steam and other Skins like Metro display fine although I asume it's because they don't style their TextEntrys quite this complicated.

**Comment by TekFolf** [comment]
I can confirm that this issue is present both in stable and beta.
![settings_2015-04-05_21-46-41](https://cloud.githubusercontent.com/assets/5775431/6998549/7fd47c30-dbdd-11e4-96dc-4d23b8d8e75f.png)


I too are wondering what caused this.

**Comment by DirtDiglett** [comment]
After having a chat with Inhibitor (The creator of the Air skin, where this issue wasn't occuring) He's figured out the cause. There was no 'base' font being set in steamscheme.res, and because of this Steam threw internal errors of "No valid font found". It looks like these input boxes take their font and style from steamscheme.res still (The file that pre-2010 olive steam used for its styling).
