### ISSUE TITLE
Different color in game detail background

### ISSUE THREAD

**Issue by ilducesaint** [DirtDiglett/Pressure-for-Steam#259]
well, i don't know if this is a issue but anyway, i get this in game detail background:
http://postimg.org/image/462usrsht/full/
so much green
when in the preview images of the skin are like this:
http://ns1.onteh.net.au/pressureskin/game-details.png

i hope you will fix it soon(if it's an issue of course), thanks for your time.

**Comment by Js41637** [comment]
Not exactly an issue, Dirt did add an overlay background and personally, mine looks like this as well, not like the preview, it is very noticeable and can hardly see the actual image behind.

**Comment by DirtDiglett** [comment]
Yeah It's intentional but I am experimenting with it to get a nice look. I'll likely drop it down to 50% Opacity soon.

**Comment by DirtDiglett** [comment]
This has been adjusted in the latest commit.

In the preview image I was using a temporary background that I didn't plan on sticking with. I've since changed it to a very similar background to what was used in the original mockups (And the Steam group icon), which is why it looks different.

I've now dropped it down to 50% opacity, as well as made the game image fully opaque so it's visible.

Closing.
