### ISSUE TITLE
Scroll bar not stylized

### ISSUE THREAD

**Issue by GOGO98901** [DirtDiglett/Pressure-for-Steam#262]
I just downloaded the latest commit and noticed that the scroll bar is no longer styled but only on the webpages the friends pane and such like are fine
<img src="http://i.imgur.com/9S8Cnd5.png" />

**Comment by DirtDiglett** [comment]
This is 100% intentional. It is styled, it's just styled in the same manner as Chrome and Chromium. Unfortunately there's no way to have the scrollbar the same way as the normal scrollbars which makes me sad, so I went with something that will also help reinforce that you're looking at a webpage vs client.

**Comment by CronosDage** [comment]
it's much larger than chrome's 3px scrollbar (albeit for me) though and looks out of place. probably because you can't resize the bar? i'd take steam's mediocre default scrollbar over this
