### ISSUE TITLE
Some texts are extremely unreadable

### ISSUE THREAD

**Issue by KIDINK** [DirtDiglett/Pressure-for-Steam#278]
Black on grey? Come on...
For example, the list of not installed software.
Or this uncheckable checkbox in upper right corner
![default](https://cloud.githubusercontent.com/assets/1337953/7137139/c612f382-e2bf-11e4-9f23-e2f38f6cf9bc.png)

**Comment by KIDINK** [comment]
The common problem persists on displays with low view angles, that's why the color scheme of 'not installed games and apps' should be changed.

**Comment by J5lx** [comment]
I personally have not the slightest problems reading that text. Just the white bullet point next to the black/dark grey text in that little popup sticks out quite a bit, but that's another issue.

**Comment by DirtDiglett** [comment]
>Black on grey? Come on...

Starting of your message aggressive and rudely really isn't very polite.

>The common problem persists on displays with low view angles, that's why the color scheme of 'not installed games and apps' should be changed.

If you've calibrated your monitor correctly and use the appropriate viewing angle for your monitor there shouldn't be an issue. By the sounds of it if you're seeing the background as black you're miscalibrated because it is grey and clearly so. I have no issues seeing the difference on any of my screens at any viewing angle.

Having said that, i've pushed an update that adds the ability to choose from a 'high contrast' option. Open the options.ini and edit appropriately, since it solves the issue and wasn't hard to do.

Enjoy.

**Comment by KIDINK** [comment]
I own old Philips 190C7F (75Hz) and using maximum color correction boost (+100% via nvidia settings), Brightness 80%, Contrast 50%.
BTW thank you for this fix (:
