### ISSUE TITLE
FriendList Friends/Groups buttons are wrongpos

### ISSUE THREAD

**Issue by KIDINK** [DirtDiglett/Pressure-for-Steam#286]
I'll try to explain it as simple as i can...
Screenshot will make it better (:
1. Open friend list
2. Move your mouse cursor to these buttons
3. Right corner of 'Friends button' will highlight Group button, pressing Friends button will open Groups tab.
4. Pressing the right corner of Groups button has no effect at all
Well, move around that buttons and see that they are completely wrong posed.
Green zone - zone, where GROUPS button become highlighted as soon as you move cursor on it
Red zone - same, for FRIENDS button
![qip shot - screen 001](https://cloud.githubusercontent.com/assets/1337953/7158852/93fd355c-e386-11e4-9c38-f073fb704294.png)

**Comment by DirtDiglett** [comment]
Hi @KIDINK,

Unfortunately this is something that won't/can't be fixed. These are technically tabs and are the buggiest and most frustrating things in the entire skin for me. In order to make them 'look' like toggle buttons there was a lot of trickery and hackery needed to do so. This is the best that FlaminSarge and I could get working within reason.

It was a choice between having them work exactly as they look, but this means they would only be the width outlined in your image by the red and green boxes. This causes them to look rather thin compared to every other button and tab on the skin.

Having said that, while typing this out I had a bit of a think and *might* have a better way of doing it i'll experiment with and try in the coming days.

**Comment by DirtDiglett** [comment]
Hi @KIDINK,

After further review and a lot of testing and experimentation unfortunately my idea couldn't come to fruition.

Unfortunately this is how these buttons will remain for the foreseeable future.

Closing as they are working as expected.
