### ISSUE TITLE
Friends List

### ISSUE THREAD

**Issue by hdoria** [DirtDiglett/Pressure-for-Steam#304]
I found a bug with my search bar (on friends list):

![2015-04-22 at 11 07](https://cloud.githubusercontent.com/assets/73786/7276413/d3fd1fce-e8df-11e4-9752-533753fd65d1.png)

Running OS X Yosemite 10.10.4 on a Macbook Retina.

**Comment by FlaminSarge** [comment]
The spacing on the FriendPanels for each person seems off; are you sure you're on the latest version?

**Comment by CorruptComputer** [comment]
It also doesn't look like the same font to me.

![capture](https://cloud.githubusercontent.com/assets/5573038/7289978/8fd52fd6-e93d-11e4-8d9b-c122acc8baf2.PNG)

**Comment by DirtDiglett** [comment]
@FlaminSarge & @CorruptComputer, he's using a Retina Mac. OSX renders fonts differently to Windows, same as Linux renders differently too. There's probably also leftover OSX-specific styles I haven't removed for it.

@hdoria in regards to the issue itself, it's tricky because Valve haven't yet fixed the bugs with background images in Retina Macs, so i've been using workarounds to try to alleviate it from occuring (Stretching images instead of repeating them, see #207 ). 

What it's doing is adding a 1 pixel wide black line between any repeating images, so in this case I stretch the image to fit the entire width, so it's stretching that black line too causing this fake gradient.

I can't test it myself as I don't have a retina mac, but can you check the normal search input, without clicking in it (So it's not highlighted blue) does the issue occur?

**Comment by FlaminSarge** [comment]
I thought we had fixed all the OSX-specific style lines for the FriendsDialog a few commits ago, which is why I was asking. Is it pulling the style from somewhere else?

**Comment by hdoria** [comment]
Works fine now (after 103476cc1103088662bccc0d518f4f296a3b80fc). Thanks.
