### ISSUE TITLE
Overlap in steam in-game overlay

### ISSUE THREAD

**Issue by fatek** [DirtDiglett/Pressure-for-Steam#373]
While playing in offline mode, the text under "View All Friends" stretches far to the right and enters "View Players" territory.

![overlap_in_overlay_offline](https://cloud.githubusercontent.com/assets/12451793/8126899/ac668348-10a7-11e5-80bc-a8176a02d9bc.png)

I noticed this also occurs in online mode, but it's not quite as bad.

![overlap_in_overlay_online](https://cloud.githubusercontent.com/assets/12451793/8126898/ac6520ca-10a7-11e5-800d-69ef820d5d37.png)

I am using the Linux version of steam on Linux Mint 17.

**Comment by FlaminSarge** [comment]
This happens if you have friends in the same server as you, as well. I'm trying to figure out a good way to deal with it, since the way Valve set up the buttons it's really hard to remove the icon for just one of the two buttons there.

**Comment by DirtDiglett** [comment]
This is something that can't be reasonably fixed in the current design of Pressure - Being horizontal means it needs to work reasonably anywhere from a resolution of 1024x768 up to 4K displays, so this was a width that I could get working for most.

At this stage it's not going to be fixed, but when I re-do the project like I intend to the design of the overlay will be vertical to resolve lots of overlay problems.
