### ISSUE TITLE
Download bar is bugged?

### ISSUE THREAD

**Issue by crunzaty** [DirtDiglett/Pressure-for-Steam#395]
After downloading the newest commit of Pressure for steam the download page on steam seems to be a bit bugged. I don't know if this is intentional but earlier the small bars on the top left filled the area marked in red.

![ss 2015-07-14 at 05 07 00](https://cloud.githubusercontent.com/assets/9476353/8676698/56a59512-2a4b-11e5-890a-d531964b59a2.jpg)

I'm using Windows 8.1 if that's important.

**Comment by Zerathos** [comment]
You need to use the beta client, see #394. This likely occurs because the beta client has disc activity in addition to download speed on that graph, which the stable client does not, so it doesn't know what to do when the skin tries to add it and breaks.

Alternatively, if the beta client is absolutely not an option, using some recent version of downloadsummarypanel.layout that is older than commit 8682ffd should work until this change is moved to the stable client branch; if you still have the old version of the skin you were using before now just grab the file from that and it should work fine. Or switch to the beta client and get a cool graph! Whatever works.

**Comment by crunzaty** [comment]
Oh, thank you! :D
