### ISSUE TITLE
Game cache validation window has cutoff text

### ISSUE THREAD

**Issue by s0r00t** [DirtDiglett/Pressure-for-Steam#401]
![Screenshot of the window](http://i.imgur.com/tdNGXlr.png) 

French locale, Arch x64, latest version from stable branch.
-The title of the windows is cutoff at the end.
-Its content is cutoff at the top and the bottom.

**Comment by bykidi** [comment]
Arch-specific bug, imo
Can't conform that on Win10.10240
![default](https://cloud.githubusercontent.com/assets/1337953/8987195/77a00be0-36e8-11e5-984a-394586520beb.PNG)
![2](https://cloud.githubusercontent.com/assets/1337953/8987196/77a26f98-36e8-11e5-9fd1-4970bc327289.PNG)

**Comment by bykidi** [comment]
Do you really have properly installed fonts included in skin folder?

**Comment by s0r00t** [comment]
If I did not install the fonts the whole theme would be fucked :P

**Comment by Zerathos** [comment]
The dialog text is too small to be cut regardless in that example, but the title isn't. The second example should be exactly the same as yours. Both say "Validation des fichiers Steam - Progression : 100%", but yours overflows its boundaries whereas this one doesn't. I don't think it's an issue of improperly-installed fonts though; Linux uses a different font in places (Arial instead of Segoe UI), so some things won't show up correctly without specific adjustment for it.

**Comment by Zerathos** [comment]
Huh, now that I'm actually looking into it it seems Linux doesn't have its own font anymore. 23e552b was where the change was made, but I forgot about the Noto Sans switch which apparently unified the platforms. If you're sure you followed the instructions in the readme when installing the font though, I'm not really sure what else it could be other than some random difference in font rendering in Linux.

**Comment by s0r00t** [comment]
I did follow all the steps, I set up a shell script to update Pressure if needed at the startup of steam, based on the original repo, Stable branch.

(BTW, the markup is fucked up at some point, the Pro tip)
