### ISSUE TITLE
Glitchy URL bar on OS X

### ISSUE THREAD

**Issue by Long-Horse** [DirtDiglett/Pressure-for-Steam#407]
Looks like this https://puu.sh/jlT7P/a378201ac1.png

There's something going on surrounding the circle loading icon and there's also some color changing from around the middle to the right side of it.

Info: Latest Steam, latest Pressure, OS X 10.10.4

**Comment by DirtDiglett** [comment]
Hey @Long-Horse sorry for the delayed response, that image doesn't load so I can't see what you're referencing.

Can you please upload directly to Git by dragging it into the comment box, or uploading it to a more permanant host like imgur.com.

**Comment by Long-Horse** [comment]
<img width="971" alt="screen shot 2015-08-16 at 10 10 19 pm" src="https://cloud.githubusercontent.com/assets/8702295/9296854/bc1f53ce-4463-11e5-96bf-20b55ef2944f.png">

**Comment by DirtDiglett** [comment]
Ok, I can tell you're using a retina display as this bug only appears on retina displays. This is due to a bug in how default steam handles tiling images; They won't tile properly on retina display and instead tile every third pixel making it look horrid. Valve haven't fixed this yet, so they just don't have any tiling images in their default skin.

My workaround was instead to stretch an image to full width, which works in most places but sometimes still bugs out as you can see here. Unfortunately it's not something I can fix reasonably so it's not very high on the to-do list.

**Comment by Long-Horse** [comment]
Alright, thankfully it's not a major problem since it's not easily fixed. I guess I can't really expect you to fix it anytime soon since Mac and even moreso, Retina Mac users aren't a very big portion of the Steam userbase. Your skin is by far my favorite of anything I've used, though, so I'd like to thank you for that :)
