### ISSUE TITLE
Extra Space on Desktop Notification

### ISSUE THREAD

**Issue by MrAmos123** [DirtDiglett/Pressure-for-Steam#461]
Description of the issue.

There's a bit of extra padding on the bottom of a notification, it hurts my eyes.

Does it also occur on Steam without the skin installed?

No

Are you in the Steam BETA? If so, does the issue occur when opted out of the BETA?

No

What Operating System are you using? (Windows 10, Mac OSX 11.1, Linux, Ubuntu etc.)

Windows 10

Are you using the latest stable release or using the latest commit version?

Yes

A screenshot of the issue.

http://i.imgur.com/am4TKpl.png - Actual Image
http://i.imgur.com/NxsguG7.png - What I mean if you don't quite understand.

Steps to reproduce the issue.

Get a notification on Windows.

**Comment by Js41637** [comment]
I'm sorry but how does it hurt your eyes to have a tiny bit of extra space on the notifications?

**Comment by KIPdeKIP** [comment]
By "hurts my eyes" they probably meant it looks ugly.
I'm for keeping it since it provides some spacing between multiple notifications.

I'd like to know if there is any functional reason why that padding is there though?
Something like multi-line game names not being cut off or a sizing restriction.

**Comment by Js41637** [comment]
I'm pretty sure it is required for long messages also it would be quite small without it.

**Comment by DirtDiglett** [comment]
...That's Pressure2, not Pressure Classic.

clooooooosed.
